local UnityEngine = clr.UnityEngine
local Vector3 = UnityEngine.Vector3

local TrainConst = {
    GATE1 = Vector3(55, 1.4, 0),
    GATE2 = Vector3(-55, 1.4, 0),

    MAIN_BROADCAST_SPOT = Vector3(0, 10, -36),
    LEFT_SIDE_BROADCAST_SPOT = Vector3(-44, 5, -40),
    RIGHT_SIDE_BROADCAST_SPOT = Vector3(44, 5, -40),

    MAIN_BROADCAST_SPOT_MAX_X_OFFSET = 15,
    MAIN_BROADCAST_SPOT_RESP0NSE_Y_OFFSET = 10,
    MAIN_BROADCAST_SPOT_STANDARD_Z_DISTANCE = 40,
    MAIN_BROADCAST_SPOT_Z_DISTANCE_TOLERANCE = 5,
    MAIN_BROADCAST_SPOT_MIN_Z_VALUE = -53,
    SIDE_CAMERA_OPEN_X_DISTANCE = 36,
    SIDE_CAMERA_OPEN_Z_VALUE = -9.16,
    LEAST_BROADCAST_LAST_TIME = 3.0,

    CAMERA_DEFOLLOW_DISTANCE_BEHIND = 20,
    CAMERA_DEFOLLOW_HEIGHT_BEHIND = 10,

    PIT_LENGTH_HALF = 55,

    GOAL_CROSSBAR_HEIGHT = 2.44,
    GOAL_POST_DISTANCE = 7.32,
    GOAL_POST_DISTANCE_HALF = 3.66,
    TRAIN_DRIBBLE_MAX_CLICK = 50,

    DEFAULT_BALL_ROTATE_ANGLE_PER_FRAME = 53,
    BALL_RADIUS = 0.1,
}

return TrainConst
