-- Generated by code. Do NOT modify this file manually.
local DemoMatchConfig = {}

DemoMatchConfig.SceneType = {
    DeadBall = 0,
    BlackScreen = 1,
    MatchClip = 2,
}

DemoMatchConfig.DialogType = {
    CoachNarrate = 0,
    CoachShout = 1,
    CRBoard = 2,
    Note = 3,
    ScoreBoard = 4,
    ShootFixTargetPosition = 5,
    HeroOneOption = 6,
    ShootFree = 7,
    FadeDialog = 8,
}

DemoMatchConfig.SceneId = {
    EnterStadium = 1,
    Prematch = 2,
    MessiFirst = 3,
    AfterMessiFirst = 4,
    MessiSecond = 5,
    AfterMessiSecond = 6,
    MessiThird = 7,
    AfterMessiThird = 8,
    HalfTimeExit = 9,
    HalfTimeLockerRoom = 10,
    CRCornerKick = 11,
    AfterCRCornerKick = 12,
    CRHero = 13,
    AfterCRHero = 14,
    CRDiving = 15,
    AfterDiving1 = 16,
    AfterDiving2 = 17,
    AfterDiving3 = 18,
    PrePenalty = 19,
    CRPenalty = 20,
    AfterPenalty1 = 21,
    AfterPenalty2 = 22,
    AfterPenalty3 = 23,
    GameOver = 24,
}

DemoMatchConfig.Scenes = {
    --EnterStadium
    [1] = {
        sceneId = 1,
        sceneType = 0,
        dialogList = {
        },
    },
    --Prematch
    [2] = {
        sceneId = 2,
        sceneType = 1,
        dialogList = {
            [1] = {
                dialogId = 1,
                type = 0,
                items = {
                    [1] = "demoMatchDialog1",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
            [2] = {
                dialogId = 2,
                type = 1,
                items = {
                    [1] = "demoMatchDialog2",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
            [3] = {
                dialogId = 3,
                type = 2,
                items = {
                    [1] = "demoMatchCR1",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
            [4] = {
                dialogId = 4,
                type = 3,
                items = {
                    [1] = "demoMatchNote0",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
        },
    },
    --MessiFirst
    [3] = {
        sceneId = 3,
        sceneType = 2,
        dialogList = {
        },
    },
    --AfterMessiFirst
    [4] = {
        sceneId = 4,
        sceneType = 1,
        dialogList = {
            [1] = {
                dialogId = 1,
                type = 4,
                items = {
                    [1] = "demoMatchScore1",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
            [2] = {
                dialogId = 2,
                type = 0,
                items = {
                    [1] = "demoMatchDialog3",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
        },
    },
    --MessiSecond
    [5] = {
        sceneId = 5,
        sceneType = 2,
        dialogList = {
        },
    },
    --AfterMessiSecond
    [6] = {
        sceneId = 6,
        sceneType = 1,
        dialogList = {
            [1] = {
                dialogId = 1,
                type = 4,
                items = {
                    [1] = "demoMatchScore2",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
            [2] = {
                dialogId = 2,
                type = 0,
                items = {
                    [1] = "demoMatchDialog4",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
        },
    },
    --MessiThird
    [7] = {
        sceneId = 7,
        sceneType = 2,
        dialogList = {
        },
    },
    --AfterMessiThird
    [8] = {
        sceneId = 8,
        sceneType = 1,
        dialogList = {
            [1] = {
                dialogId = 1,
                type = 4,
                items = {
                    [1] = "demoMatchScore3",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
            [2] = {
                dialogId = 2,
                type = 0,
                items = {
                    [1] = "demoMatchDialog5",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
        },
    },
    --HalfTimeExit
    [9] = {
        sceneId = 9,
        sceneType = 0,
        dialogList = {
        },
    },
    --HalfTimeLockerRoom
    [10] = {
        sceneId = 10,
        sceneType = 1,
        dialogList = {
            [1] = {
                dialogId = 1,
                type = 3,
                items = {
                    [1] = "demoMatchNote1",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
            [2] = {
                dialogId = 2,
                type = 1,
                items = {
                    [1] = "demoMatchDialog6",
                    [2] = "demoMatchDialog7",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
            [3] = {
                dialogId = 3,
                type = 2,
                items = {
                    [1] = "demoMatchCR2",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
            [4] = {
                dialogId = 4,
                type = 1,
                items = {
                    [1] = "demoMatchDialog9",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
        },
    },
    --CRCornerKick
    [11] = {
        sceneId = 11,
        sceneType = 2,
        dialogList = {
            [1] = {
                dialogId = 1,
                type = 1,
                items = {
                    [1] = "demoMatchDialog10",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
            [2] = {
                dialogId = 2,
                type = 5,
                items = {
                },
                audioOnShow = {
                },
                audioOnDismiss = "sm_comment_6",
            },
            [3] = {
                dialogId = 3,
                type = 1,
                items = {
                    [1] = "demoMatchDialog11",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
        },
    },
    --AfterCRCornerKick
    [12] = {
        sceneId = 12,
        sceneType = 1,
        dialogList = {
            [1] = {
                dialogId = 1,
                type = 4,
                items = {
                    [1] = "demoMatchScore4",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
            [2] = {
                dialogId = 2,
                type = 1,
                items = {
                    [1] = "demoMatchDialog12",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
        },
    },
    --CRHero
    [13] = {
        sceneId = 13,
        sceneType = 2,
        dialogList = {
            [1] = {
                dialogId = 1,
                type = 0,
                items = {
                    [1] = "demoMatchDialog14",
                },
                audioOnShow = {
                    [1] = "sm_comment_7",
                },
                audioOnDismiss = nil,
            },
            [2] = {
                dialogId = 2,
                type = 1,
                items = {
                    [1] = "demoMatchDialog15",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
            [3] = {
                dialogId = 3,
                type = 6,
                items = {
                },
                audioOnShow = {
                },
                audioOnDismiss = "sm_comment_8",
            },
            [4] = {
                dialogId = 4,
                type = 0,
                items = {
                    [1] = "demoMatchDialog16",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
            [5] = {
                dialogId = 5,
                type = 6,
                items = {
                },
                audioOnShow = {
                },
                audioOnDismiss = "sm_comment_9",
            },
            [6] = {
                dialogId = 6,
                type = 0,
                items = {
                    [1] = "demoMatchDialog18",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
            [7] = {
                dialogId = 7,
                type = 6,
                items = {
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
            [8] = {
                dialogId = 8,
                type = 5,
                items = {
                },
                audioOnShow = {
                },
                audioOnDismiss = "sm_comment_10",
            },
            [9] = {
                dialogId = 9,
                type = 1,
                items = {
                    [1] = "demoMatchDialog20",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
        },
    },
    --AfterCRHero
    [14] = {
        sceneId = 14,
        sceneType = 1,
        dialogList = {
            [1] = {
                dialogId = 1,
                type = 4,
                items = {
                    [1] = "demoMatchScore5",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
            [2] = {
                dialogId = 2,
                type = 1,
                items = {
                    [1] = "demoMatchDialog21",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
        },
    },
    --CRDiving
    [15] = {
        sceneId = 15,
        sceneType = 2,
        dialogList = {
        },
    },
    --AfterDiving1
    [16] = {
        sceneId = 16,
        sceneType = 0,
        dialogList = {
        },
    },
    --AfterDiving2
    [17] = {
        sceneId = 17,
        sceneType = 1,
        dialogList = {
        },
    },
    --AfterDiving3
    [18] = {
        sceneId = 18,
        sceneType = 0,
        dialogList = {
        },
    },
    --PrePenalty
    [19] = {
        sceneId = 19,
        sceneType = 1,
        dialogList = {
            [1] = {
                dialogId = 1,
                type = 0,
                items = {
                    [1] = "demoMatchDialog22",
                    [2] = "demoMatchDialog23",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
        },
    },
    --CRPenalty
    [20] = {
        sceneId = 20,
        sceneType = 2,
        dialogList = {
            [1] = {
                dialogId = 1,
                type = 7,
                items = {
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
        },
    },
    --AfterPenalty1
    [21] = {
        sceneId = 21,
        sceneType = 0,
        dialogList = {
        },
    },
    --AfterPenalty2
    [22] = {
        sceneId = 22,
        sceneType = 1,
        dialogList = {
        },
    },
    --AfterPenalty3
    [23] = {
        sceneId = 23,
        sceneType = 0,
        dialogList = {
        },
    },
    --GameOver
    [24] = {
        sceneId = 24,
        sceneType = 1,
        dialogList = {
            [1] = {
                dialogId = 1,
                type = 0,
                items = {
                    [1] = "demoMatchDialog25",
                    [2] = "demoMatchDialog26",
                    [3] = "demoMatchDialog27",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
            [2] = {
                dialogId = 2,
                type = 3,
                items = {
                    [1] = "demoMatchNote2",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
            [3] = {
                dialogId = 3,
                type = 8,
                items = {
                    [1] = "demoMatchFadeDialog1",
                    [2] = "demoMatchFadeDialog2",
                    [3] = "demoMatchFadeDialog3",
                    [4] = "demoMatchFadeDialog4",
                    [5] = "demoMatchFadeDialog5",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
            [4] = {
                dialogId = 4,
                type = 3,
                items = {
                    [1] = "demoMatchNote3",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
            [5] = {
                dialogId = 5,
                type = 0,
                items = {
                    [1] = "demoMatchDialog29",
                    [2] = "demoMatchDialog30",
                    [3] = "demoMatchDialog31",
                },
                audioOnShow = {
                },
                audioOnDismiss = nil,
            },
        },
    },
}

DemoMatchConfig.MatchClips = {
    --MessiFirst
    [3] = {
        path = "Assets/CapstonesRes/Game/Config/DemoMatch/[137.8]GoalKick-[156.1]GoalKick.asset",
        loadStartTime = 151.4,
        inGameStartTime = 20,
        playbackLength = 0,
        playbackStartEvent = 3,
        loadDelay = 0,
        audio = "sm_comment_2",
        audioDelay = 0.8,
    },
    --MessiSecond
    [5] = {
        path = "Assets/CapstonesRes/Game/Config/DemoMatch/[126.9]TimedKickOff-[172]TimedKickOff.asset",
        loadStartTime = 168.5,
        inGameStartTime = 60,
        playbackLength = 0,
        playbackStartEvent = 3,
        loadDelay = 0,
        audio = "sm_comment_3",
        audioDelay = 0,
    },
    --MessiThird
    [7] = {
        path = "Assets/CapstonesRes/Game/Config/DemoMatch/[110.5]WingDirectFreeKick-[115.8]TimedKickOff.asset",
        loadStartTime = 110.5,
        inGameStartTime = 89,
        playbackLength = 0,
        playbackStartEvent = 7,
        loadDelay = 0,
        audio = "sm_comment_3s",
        audioDelay = 0.8,
    },
    --CRCornerKick
    [11] = {
        path = "Assets/CapstonesRes/Game/Config/DemoMatch/[24.4]CornerKick-[30.6]CornerKick.asset",
        loadStartTime = 24.4,
        inGameStartTime = 110,
        playbackLength = 4.1,
        playbackStartEvent = 12,
        loadDelay = 0,
        audio = "sm_comment_5",
        audioDelay = 2,
    },
    --CRHero
    [13] = {
        path = "Assets/CapstonesRes/Game/Config/DemoMatch/[0.1]NontimedKickOff-[19.6]TimedKickOff_hero.asset",
        loadStartTime = 8.7,
        inGameStartTime = 140,
        playbackLength = 5,
        playbackStartEvent = 3,
        loadDelay = 0,
        audio = nil,
        audioDelay = 0,
    },
    --CRDiving
    [15] = {
        path = "Assets/CapstonesRes/Game/Config/DemoMatch/[37.6]GoalKick-[53.1]PenaltyKick.asset",
        loadStartTime = 50.2,
        inGameStartTime = 172,
        playbackLength = 0,
        playbackStartEvent = 0,
        loadDelay = 0,
        audio = "sm_comment_11",
        audioDelay = 0,
    },
    --CRPenalty
    [20] = {
        path = "Assets/CapstonesRes/Game/Config/DemoMatch/[49.5]PenaltyKick-[51.6]TimedKickOff.asset",
        loadStartTime = 49.5,
        inGameStartTime = 178,
        playbackLength = 2.1,
        playbackStartEvent = 5,
        loadDelay = 0,
        audio = nil,
        audioDelay = 0,
    },
}

DemoMatchConfig.DeadBallScenes = {
    --EnterStadium
    [1] = {
        [1] = {
            type = "GroupEnter",
            idx = 1,
            x = -32,
            z = -52,
            ids = { 20,11,17,19,13,14,12,15,16,18,21,1,0,2,3,4,5,6,7,8,9,10 },
            allowSkip = true,
            delay = 3,
            applyActionToRest = false,
            audio = "sm_comment_1",
        },
        [2] = {
            type = "SoloEnter",
            idx = 1,
            x = -25,
            z = -38,
            ids = { 20 },
            allowSkip = true,
            delay = 3,
            applyActionToRest = false,
            audio = nil,
        },
        [3] = {
            type = "SoloEnter",
            idx = 3,
            x = -25,
            z = -38,
            ids = { 1 },
            allowSkip = true,
            delay = 3,
            applyActionToRest = false,
            audio = nil,
        },
        [4] = {
            type = "HandShake",
            idx = 1,
            x = -15,
            z = 0,
            ids = { 1,20,22,23,24 },
            allowSkip = true,
            delay = 3,
            applyActionToRest = false,
            audio = nil,
        },
        [5] = {
            type = "WaitKickOff",
            idx = 1,
            x = 0,
            z = 0,
            ids = { 14 },
            allowSkip = true,
            delay = 3,
            applyActionToRest = false,
            audio = nil,
        },
    },
    --MessiFirst
    [3] = {
        [1] = {
            type = "Goal",
            idx = 4,
            x = -25,
            z = -49,
            ids = { 14,17,20,10,0 },
            allowSkip = false,
            delay = 0,
            applyActionToRest = false,
            audio = nil,
        },
    },
    --MessiSecond
    [5] = {
        [1] = {
            type = "GoalStep2",
            idx = 1,
            x = -25,
            z = -49,
            ids = { 14,17,19 },
            allowSkip = false,
            delay = 0.5,
            applyActionToRest = false,
            audio = nil,
        },
    },
    --MessiThird
    [7] = {
        [1] = {
            type = "GoalStep2",
            idx = 3,
            x = -25,
            z = -49,
            ids = { 20,8,0,10 },
            allowSkip = false,
            delay = 0.5,
            applyActionToRest = false,
            audio = nil,
        },
    },
    --HalfTimeExit
    [9] = {
        [1] = {
            type = "HalfExitLose",
            idx = 1,
            x = -28,
            z = -44,
            ids = { 1 },
            allowSkip = false,
            delay = 0,
            applyActionToRest = false,
            audio = "sm_comment_4",
        },
        [2] = {
            type = "HalfExitLose",
            idx = 3,
            x = -28,
            z = -44,
            ids = { 1,6 },
            allowSkip = false,
            delay = 0,
            applyActionToRest = false,
            audio = nil,
        },
    },
    --CRCornerKick
    [11] = {
        [1] = {
            type = "GoalPickupBall",
            idx = 2,
            x = 0,
            z = -55,
            ids = { 1,11 },
            allowSkip = false,
            delay = 0,
            applyActionToRest = false,
            audio = nil,
        },
    },
    --CRHero
    [13] = {
        [1] = {
            type = "GoalPickupBall",
            idx = 1,
            x = 0,
            z = -55,
            ids = { 1,11 },
            allowSkip = false,
            delay = 0,
            applyActionToRest = false,
            audio = nil,
        },
    },
    --AfterDiving1
    [16] = {
        [1] = {
            type = "ArgueWithRef",
            idx = 2,
            x = 19,
            z = -45,
            ids = { 20 },
            allowSkip = false,
            delay = 0,
            applyActionToRest = false,
            audio = nil,
        },
    },
    --AfterDiving3
    [18] = {
        [1] = {
            type = "SetBallPenalty",
            idx = 1,
            x = 0,
            z = -44,
            ids = { 1,19,2,17,20,3,4,14 },
            allowSkip = false,
            delay = 0,
            applyActionToRest = false,
            audio = nil,
        },
    },
    --AfterPenalty1
    [21] = {
        [1] = {
            type = "MissShoot",
            idx = 9,
            x = 0,
            z = -44,
            ids = { 1 },
            allowSkip = false,
            delay = 0,
            applyActionToRest = false,
            audio = nil,
        },
    },
    --AfterPenalty3
    [23] = {
        [1] = {
            type = "OverExitLose",
            idx = 1,
            x = -25,
            z = -35,
            ids = { 1,5 },
            allowSkip = false,
            delay = 0,
            applyActionToRest = false,
            audio = nil,
        },
        [2] = {
            type = "OverExitLoseStep2",
            idx = 1,
            x = -20,
            z = -25,
            ids = { 20,1 },
            allowSkip = false,
            delay = 0,
            applyActionToRest = false,
            audio = nil,
        },
        [3] = {
            type = "HalfExitLose",
            idx = 2,
            x = -28,
            z = -44,
            ids = { 1 },
            allowSkip = false,
            delay = 0,
            applyActionToRest = false,
            audio = nil,
        },
    },
}

return DemoMatchConfig
