return {
    baseInfo = {
        randSeed = 732530806,
        battleType = "friendShip",
        home = 0,
        isReplay = false,
        matchType = 2,
        weather = "sun",
        tips = lang.trans("demoMatchTip")
    },
    opponent = {
        startId = 12,
        athletes = {
            {--12    David Silva
                abilities = {
                    dribble = 21303,
                    intercept = 6312,
                    pass = 16676,
                    save = 1830,
                    shoot = 71582,
                    steal = 5744,
                },
                adeptRole = {
                    2,
                    3,
                    4,
                },
                role = 3,
                skills = {
                },
                onfieldId = 13,
                id = 12,
                cid = "SMSpain3",
                number = 21,
            },
            {--13    A. Iniesta
                abilities = {
                    dribble = 10170,
                    intercept = 39393,
                    pass = 8742,
                    save = 1701,
                    shoot = 1712,
                    steal = 16404,
                },
                adeptRole = {
                    7,
                },
                role = 7,
                skills = {
                },
                onfieldId = 14,
                id = 13,
                cid = "SMSpain2",
                number = 6,
            },
            {--14    A. Morata
                abilities = {
                    dribble = 16199,
                    intercept = 28509,
                    pass = 23149,
                    save = 2782,
                    shoot = 3331,
                    steal = 58866,
                },
                adeptRole = {
                    8,
                },
                role = 8,
                skills = {
                },
                onfieldId = 15,
                id = 14,
                cid = "SMSpain1",
                number = 7,
            },
            {--15    J. Mata
                abilities = {
                    dribble = 9246,
                    intercept = 24669,
                    pass = 8984,
                    save = 1804,
                    shoot = 8761,
                    steal = 20771,
                },
                adeptRole = {
                    9,
                },
                role = 9,
                skills = {
                },
                onfieldId = 16,
                id = 15,
                cid = "SMSpain4",
                number = 13,
            },
            {--16    Isco
                abilities = {
                    dribble = 52354,
                    intercept = 6229,
                    pass = 46482,
                    save = 3059,
                    shoot = 22939,
                    steal = 6229,
                },
                adeptRole = {
                    2,
                    3,
                    4,
                    5,
                    10,
                    7,
                    8,
                    9,
                    12,
                    13,
                    14,
                    15,
                },
                role = 12,
                skills = {
                },
                onfieldId = 17,
                id = 16,
                cid = "SMSpain6",
                number = 22,
            },
            {--17    S. Busquets
                abilities = {
                    dribble = 4532,
                    intercept = 59979,
                    pass = 6429,
                    save = 1638,
                    shoot = 5786,
                    steal = 17304,
                },
                adeptRole = {
                    14,
                    23,
                    24,
                },
                role = 14,
                skills = {
                },
                onfieldId = 18,
                id = 17,
                cid = "SMSpain5",
                number = 5,
            },
            {--18    C. Azpilicueta
                abilities = {
                    dribble = 32775,
                    intercept = 2408,
                    pass = 19700,
                    save = 1602,
                    shoot = 22747,
                    steal = 2731,
                },
                adeptRole = {
                    1,
                    6,
                    5,
                    10,
                    11,
                    21,
                    7,
                    8,
                    9,
                    2,
                    3,
                    4,
                },
                role = 21,
                skills = {
                },
                onfieldId = 19,
                id = 18,
                cid = "SMSpain7",
                number = 18,
            },
            {--19    G. Pique
                abilities = {
                    dribble = 8203,
                    intercept = 22810,
                    pass = 8531,
                    save = 1564,
                    shoot = 1234,
                    steal = 29625,
                },
                adeptRole = {
                    22,
                    18,
                    19,
                    12,
                    13,
                    14,
                },
                role = 22,
                skills = {
                },
                onfieldId = 20,
                id = 19,
                cid = "SMSpain8",
                number = 3,
            },
            {--20    Sergio Ramos
                abilities = {
                    dribble = 9391,
                    intercept = 6266,
                    pass = 22609,
                    save = 1774,
                    shoot = 64398,
                    steal = 6266,
                },
                adeptRole = {
                    24,
                },
                role = 24,
                skills = {
                },
                onfieldId = 21,
                id = 20,
                cid = "SMSpain9",
                number = 15,
            },
            {--21    D. Carvajal
                abilities = {
                    dribble = 11752,
                    intercept = 18158,
                    pass = 8773,
                    save = 1716,
                    shoot = 1716,
                    steal = 36777,
                },
                adeptRole = {
                    20,
                    25,
                },
                role = 25,
                skills = {
                },
                onfieldId = 22,
                id = 21,
                cid = "SMSpain10",
                number = 4,
            },
            {--11    D. De Gea
                abilities = {
                    dribble = 11359,
                    intercept = 3062,
                    pass = 9100,
                    save = 89950,
                    shoot = 3062,
                    steal = 3062,
                },
                adeptRole = {
                    26,
                },
                role = 26,
                skills = {
                },
                onfieldId = 12,
                id = 22,
                cid = "SMSpain11",
                number = 1,
            },
        },
        captain = 8,
        coachBonus = {
            AMC = {
                intercept = 0.2,
            },
            DC = {
                intercept = 0.1,
                save = 0.1,
                steal = 0.1,
            },
            DL = {
                dribble = 0.15,
                intercept = 0.1,
                save = 0.1,
                steal = 0.1,
            },
            DMC = {
                intercept = 0.2,
            },
            DR = {
                dribble = 0.15,
                intercept = 0.1,
                save = 0.1,
                steal = 0.1,
            },
            FC = {
                dribble = 0.1,
                pass = 0.1,
                shoot = 0.1,
            },
            FL = {
                dribble = 0.15,
            },
            FR = {
                dribble = 0.15,
            },
            MC = {
                intercept = 0.2,
            },
            ML = {
                dribble = 0.15,
                intercept = 0.2,
            },
            MR = {
                dribble = 0.15,
                intercept = 0.2,
            },
        },
        coachId = "10",
        coachPic = "dragan",
        coachSkill = {
            1014,
        },
        freeKick = 8,
        field = "south",
        formation = 7,
        leftCorner = 8,
        penaltyKicker = 8,
        power = 883120,
        rightCorner = 8,
        role = "Defend",
        tactics = {
            attackEmphasis = 3,
            competitionMentality = 4,
            defenseAggression = 3,
            defenseStrategy = 3,
            name = "",
            passTactic = 3,
            attackRhythm = 3,
        },
        tid = "SMSpain",
        goalKit = "menjiang1",
        sloganID = "",
        logo = "SMSpain",
        homeKit = "npc14",
        spectatorsID = "",
        awayKit = "npc13",
        teamName = lang.trans("demoMatchAwayTeamName"),
        teamID = "SMSpain",
        teamType = "npc",
        homeShirt = {
            mask = "Mask_68",
            maskRedChannel = "0.031, 0.049, 0.382, 1.000",
            maskGreenChannel = "0.000, 0.009, 0.250, 1.000",
            maskBlueChannel = "0.779, 0.748, 0.682, 1.000",
            backNumColor = "0.949, 0.803, 0.028, 1.000",
            trouNumColor = "0.945, 0.800, 0.027, 1.000",
        },
        homeGkShirt = {
            mask = "Mask_34",
            maskRedChannel = "1.000, 0.768, 0.000, 1.000",
            maskGreenChannel = "0.039, 0.039, 0.039, 1.000",
            maskBlueChannel = "0.039, 0.039, 0.039, 1.000",
            backNumColor = "0.117, 0.117, 0.117, 1.000",
            trouNumColor = "0.800, 0.800, 0.800, 1.000",
        },
    },
    ops = {
    },
    player = {
        startId = 1,
        athletes = {
            {--Ronaldo  1
                abilities = {
                    dribble = 21303,
                    intercept= 6312,
                    pass = 16676,
                    save = 1830,
                    shoot = 3421,
                    steal = 5744,
                },
                adeptRole = {
                    2,
                    3,
                    4,
                },
                role = 2,
                skills = {
                },
                onfieldId = 2,
                id = 1,
                cid = "SMPortugal1",
                number = 7,
            },
            {--Nani 2
                abilities = {
                    dribble = 10170,
                    intercept = 39393,
                    pass = 8742,
                    save = 1701,
                    shoot = 1712,
                    steal = 16404,
                },
                adeptRole = {
                    4,
                },
                role = 4,
                skills = {
                },
                onfieldId = 3,
                id = 2,
                cid = "SMPortugal2",
                number = 17,
            },
            {--Andre Gomes  3
                abilities = {
                    dribble = 16199,
                    intercept = 28509,
                    pass = 23149,
                    save = 2782,
                    shoot = 11574,
                    steal = 58866,
                },
                adeptRole = {
                    11,
                    15,
                    12,
                    13,
                    14,
                    16,
                    21,
                    20,
                    25,
                    22,
                    23,
                    24,
                    17,
                    18,
                    19,
                    2,
                    3,
                    4,
                },
                role = 11,
                skills = {
                },
                onfieldId = 4,
                id = 3,
                cid = "SMPortugal3",
                number = 15,
            },
            {--Tiago    4
                abilities = {
                    dribble = 9246,
                    intercept = 24669,
                    pass = 8984,
                    save = 1804,
                    shoot = 8761,
                    steal = 20771,
                },
                adeptRole = {
                    12,
                },
                role = 12,
                skills = {
                },
                onfieldId = 5,
                id = 4,
                cid = "SMPortugal4",
                number = 16,
            },
            {--Moutinho 5
                abilities = {
                    dribble = 52354,
                    intercept = 6229,
                    pass = 46482,
                    save = 3059,
                    shoot = 22939,
                    steal = 6229,
                },
                adeptRole = {
                    2,
                    3,
                    4,
                    5,
                    10,
                    7,
                    8,
                    9,
                    12,
                    13,
                    14,
                    15,
                },
                role = 14,
                skills = {
                },
                onfieldId = 6,
                id = 5,
                cid = "SMPortugal5",
                number = 8,
            },
            {--W. Carvalho  6
                abilities = {
                    dribble = 4532,
                    intercept = 59979,
                    pass = 6429,
                    save = 1638,
                    shoot = 5786,
                    steal = 17304,
                },
                adeptRole = {
                    15,
                },
                role = 15,
                skills = {
                },
                onfieldId = 7,
                id = 6,
                cid = "SMPortugal6",
                number = 14,
            },
            {--Coentrao 7
                abilities = {
                    dribble = 32775,
                    intercept = 2408,
                    pass = 19700,
                    save = 1602,
                    shoot = 22747,
                    steal = 2731,
                },
                adeptRole = {
                    21,
                },
                role = 21,
                skills = {
                },
                onfieldId = 8,
                id = 7,
                cid = "SMPortugal7",
                number = 5,
            },
            {--Pepe 8
                abilities = {
                    dribble = 8203,
                    intercept = 22810,
                    pass = 8531,
                    save = 1564,
                    shoot = 1234,
                    steal = 29625,
                },
                adeptRole = {
                    22,
                },
                role = 22,
                skills = {
                },
                onfieldId = 9,
                id = 8,
                cid = "SMPortugal8",
                number = 3,
            },
            {--R. Carvalho  9
                abilities = {
                    dribble = 9391,
                    intercept = 6266,
                    pass = 22609,
                    save = 1774,
                    shoot = 64398,
                    steal = 6266,
                },
                adeptRole = {
                    24,
                },
                role = 24,
                skills = {
                },
                onfieldId = 10,
                id = 9,
                cid = "SMPortugal9",
                number = 6,
            },
            {--Fonte    10
                abilities = {
                    dribble = 11752,
                    intercept = 18158,
                    pass = 8773,
                    save = 1716,
                    shoot = 1716,
                    steal = 36777,
                },
                adeptRole = {
                    20,
                    25,
                },
                role = 25,
                skills = {
                },
                onfieldId = 11,
                id = 10,
                cid = "SMPortugal10",
                number = 4,
            },
            {--Patricio 0
                abilities = {
                    dribble = 11359,
                    intercept = 3062,
                    pass = 9100,
                    save = 89950,
                    shoot = 3062,
                    steal = 3062,
                },
                adeptRole = {
                    26,
                },
                role = 26,
                skills = {
                },
                onfieldId = 1,
                id = 11,
                cid = "SMPortugal11",
                number = 1,
            },
        },
        captain = 2,
        coachBonus = {
            AMC = {
                intercept = 0.2,
            },
            DC = {
                intercept = 0.1,
                save = 0.1,
                steal = 0.1,
            },
            DL = {
                dribble = 0.15,
                intercept = 0.1,
                save = 0.1,
                steal = 0.1,
            },
            DMC = {
                intercept = 0.2,
            },
            DR = {
                dribble = 0.15,
                intercept = 0.1,
                save = 0.1,
                steal = 0.1,
            },
            FC = {
                dribble = 0.1,
                pass = 0.1,
                shoot = 0.1,
            },
            FL = {
                dribble = 0.15,
            },
            FR = {
                dribble = 0.15,
            },
            MC = {
                intercept = 0.2,
            },
            ML = {
                dribble = 0.15,
                intercept = 0.2,
            },
            MR = {
                dribble = 0.15,
                intercept = 0.2,
            },
        },
        coachId = "10",
        coachPic = "dragan",
        coachSkill = {
            1014,
        },
        freeKick = 2,
        field = "north",
        formation = 10,
        rightCorner = 4,
        penaltyKicker = 2,
        power = 883120,
        leftCorner = 4,
        role = "Attack",
        tactics = {
            attackEmphasis = 3,
            competitionMentality = 4,
            defenseAggression = 3,
            defenseStrategy = 3,
            name = "",
            passTactic = 3,
            attackRhythm = 3,
        },
        tid = "SMPortugal",
        goalKit = "menjiang2",
        sloganID = "",
        logo = "SMPortugal",
        homeKit = "npc13",
        spectatorsID = "",
        awayKit = "npc12",
        teamName = lang.trans("demoMatchHomeTeamName"),
        teamID = "SMPortugal",
        teamType = "player",
        homeShirt = {
            mask = "Mask_69",
            maskRedChannel = "0.684, 0.106, 0.214, 1.000",
            maskGreenChannel = "0.022, 0.301, 0.150, 1.000",
            maskBlueChannel = "0.456, 0.064, 0.141, 1.000",
            backNumColor = "0.117, 0.117, 0.117, 1.000",
            trouNumColor = "0.117, 0.117, 0.117, 1.000",
        },
        homeGkShirt = {
            mask = "Mask_16",
            maskRedChannel = "0.404, 0.702, 0.274, 1.000",
            maskGreenChannel = "0.231, 0.607, 0.459, 1.000",
            maskBlueChannel = "0.231, 0.607, 0.459, 1.000",
            backNumColor = "0.800, 0.800, 0.800, 1.000",
            trouNumColor = "0.800, 0.800, 0.800, 1.000",
        },
    },
}