local MatchStates = class()
MatchStates.PrepareToKickOff = import("./PrepareToKickOff")
MatchStates.NontimedKickOff = import("./NontimedKickOff")
MatchStates.TimedKickOff = import("./TimedKickOff")
MatchStates.NormalPlayOn = import("./NormalPlayOn")
MatchStates.PenaltyKick = import("./PenaltyKick")
MatchStates.CenterDirectFreeKick = import("./CenterDirectFreeKick")
MatchStates.WingDirectFreeKick = import("./WingDirectFreeKick")
MatchStates.IndirectFreeKick = import("./IndirectFreeKick")
MatchStates.Substitution = import("./Substitution")
MatchStates.ThrowIn = import("./ThrowIn")
MatchStates.GoalKick = import("./GoalKick")
MatchStates.CornerKick = import("./CornerKick")
MatchStates.PenaltyShootOutKick = import("./PenaltyShootOutKick")
MatchStates.PenaltyShootOut = import("./PenaltyShootOut")
MatchStates.GameOver = import("./GameOver")

function MatchStates:ctor(match)
    self.PrepareToKickOff = MatchStates.PrepareToKickOff.new(match)
    self.NontimedKickOff = MatchStates.NontimedKickOff.new(match)
    self.TimedKickOff = MatchStates.TimedKickOff.new(match)
    self.NormalPlayOn = MatchStates.NormalPlayOn.new(match)
    self.PenaltyKick = MatchStates.PenaltyKick.new(match)
    self.CenterDirectFreeKick = MatchStates.CenterDirectFreeKick.new(match)
    self.WingDirectFreeKick = MatchStates.WingDirectFreeKick.new(match)
    self.IndirectFreeKick = MatchStates.IndirectFreeKick.new(match)
    self.Substitution = MatchStates.Substitution.new(match)
    self.ThrowIn = MatchStates.ThrowIn.new(match)
    self.GoalKick = MatchStates.GoalKick.new(match)
    self.CornerKick = MatchStates.CornerKick.new(match)
    self.PenaltyShootOutKick = MatchStates.PenaltyShootOutKick.new(match)
    self.PenaltyShootOut = MatchStates.PenaltyShootOut.new(match)
    self.GameOver = MatchStates.GameOver.new(match)
end

return MatchStates
