return {
    baseInfo = {
        randSeed = 732530806,
        battleType = "friendShip",
        home = 1,
        isReplay = false,
        matchType = 2,
        weather = "sun",
        tips = lang.trans("demoMatchTip")
    },
    opponent = {
        startId = 12,
        athletes = {
            {--12    G. Higuain
                abilities = {
                    dribble = 21303,
                    intercept = 6312,
                    pass = 16676,
                    save = 1830,
                    shoot = 71582,
                    steal = 5744,
                },
                adeptRole = {
                    2,
                    3,
                    4,
                },
                role = 3,
                skills = {
                },
                onfieldId = 13,
                id = 12,
                cid = "SMJuventus01",
                number = 9,
            },
            {--13    P. Dybala
                abilities = {
                    dribble = 10170,
                    intercept = 39393,
                    pass = 8742,
                    save = 1701,
                    shoot = 1712,
                    steal = 16404,
                },
                adeptRole = {
                    7,
                },
                role = 7,
                skills = {
                },
                onfieldId = 14,
                id = 13,
                cid = "SMJuventus02",
                number = 21,
            },
            {--14    J. Cuadrado
                abilities = {
                    dribble = 16199,
                    intercept = 28509,
                    pass = 23149,
                    save = 2782,
                    shoot = 3331,
                    steal = 58866,
                },
                adeptRole = {
                    8,
                },
                role = 8,
                skills = {
                },
                onfieldId = 15,
                id = 14,
                cid = "SMJuventus03",
                number = 7,
            },
            {--15    K. Asamoah
                abilities = {
                    dribble = 9246,
                    intercept = 24669,
                    pass = 8984,
                    save = 1804,
                    shoot = 8761,
                    steal = 20771,
                },
                adeptRole = {
                    9,
                },
                role = 9,
                skills = {
                },
                onfieldId = 16,
                id = 15,
                cid = "SMJuventus04",
                number = 22,
            },
            {--16    C. Marchisio
                abilities = {
                    dribble = 52354,
                    intercept = 6229,
                    pass = 46482,
                    save = 3059,
                    shoot = 22939,
                    steal = 6229,
                },
                adeptRole = {
                    2,
                    3,
                    4,
                    5,
                    10,
                    7,
                    8,
                    9,
                    12,
                    13,
                    14,
                    15,
                },
                role = 12,
                skills = {
                },
                onfieldId = 17,
                id = 16,
                cid = "SMJuventus05",
                number = 8,
            },
            {--17    S. Khedira
                abilities = {
                    dribble = 4532,
                    intercept = 59979,
                    pass = 6429,
                    save = 1638,
                    shoot = 5786,
                    steal = 17304,
                },
                adeptRole = {
                    14,
                    23,
                    24,
                },
                role = 14,
                skills = {
                },
                onfieldId = 18,
                id = 17,
                cid = "SMJuventus06",
                number = 6,
            },
            {--18    Dani Alves
                abilities = {
                    dribble = 32775,
                    intercept = 2408,
                    pass = 19700,
                    save = 1602,
                    shoot = 22747,
                    steal = 2731,
                },
                adeptRole = {
                    1,
                    6,
                    5,
                    10,
                    11,
                    21,
                    7,
                    8,
                    9,
                    2,
                    3,
                    4,
                },
                role = 21,
                skills = {
                },
                onfieldId = 19,
                id = 18,
                cid = "SMJuventus07",
                number = 23,
            },
            {--19    G. Chiellini
                abilities = {
                    dribble = 8203,
                    intercept = 22810,
                    pass = 8531,
                    save = 1564,
                    shoot = 1234,
                    steal = 29625,
                },
                adeptRole = {
                    22,
                    18,
                    19,
                    12,
                    13,
                    14,
                },
                role = 22,
                skills = {
                },
                onfieldId = 20,
                id = 19,
                cid = "SMJuventus08",
                number = 3,
            },
            {--20    L. Bonucci
                abilities = {
                    dribble = 9391,
                    intercept = 6266,
                    pass = 22609,
                    save = 1774,
                    shoot = 64398,
                    steal = 6266,
                },
                adeptRole = {
                    24,
                },
                role = 24,
                skills = {
                },
                onfieldId = 21,
                id = 20,
                cid = "SMJuventus09",
                number = 19,
            },
            {--21    A. Barzagli
                abilities = {
                    dribble = 11752,
                    intercept = 18158,
                    pass = 8773,
                    save = 1716,
                    shoot = 1716,
                    steal = 36777,
                },
                adeptRole = {
                    20,
                    25,
                },
                role = 25,
                skills = {
                },
                onfieldId = 22,
                id = 21,
                cid = "SMJuventus10",
                number = 15,
            },
            {--11    G. Buffon
                abilities = {
                    dribble = 11359,
                    intercept = 3062,
                    pass = 9100,
                    save = 89950,
                    shoot = 3062,
                    steal = 3062,
                },
                adeptRole = {
                    26,
                },
                role = 26,
                skills = {
                },
                onfieldId = 12,
                id = 22,
                cid = "SMJuventus11",
                number = 1,
            },
        },
        captain = 11,
        field = "south",
        role = "Defend",
        tactics = {
            attackEmphasis = 3,
            competitionMentality = 4,
            defenseAggression = 3,
            defenseStrategy = 3,
            name = "",
            passTactic = 3,
            attackRhythm = 3,
        },
        tid = "SMJuventus",
        sloganID = "",
        logo = "JuventusPlayer",
        spectatorsID = "",
        teamID = "SMJuventus",
        teamType = "npc",
        homeShirt = {
            mask = "Mask_03",
            maskRedChannel = "0.000, 0.000, 0.000, 1.000",
            maskGreenChannel = "0.902, 0.902, 0.902, 1.000",
            maskBlueChannel = "0.000, 0.000, 0.000, 1.000",
            backNumColor = "1.000, 1.000, 0.000, 1.000",
            trouNumColor = "1.000, 1.000, 1.000, 1.000",
        },
        homeGkShirt = {
            mask = "Mask_34",
            maskRedChannel = "0.902, 0.294, 0.000, 1.000",
            maskGreenChannel = "0.902, 0.902, 0.902, 1.000",
            maskBlueChannel = "0.902, 0.294, 0.000, 1.000",
            backNumColor = "1.000, 1.000, 1.000, 1.000",
            trouNumColor = "1.000, 1.000, 1.000, 1.000",
        },
    },
    ops = {
    },
    player = {
        startId = 1,
        athletes = {
            {--R. Lewandowski  1
                abilities = {
                    dribble = 21303,
                    intercept= 6312,
                    pass = 16676,
                    save = 1830,
                    shoot = 3421,
                    steal = 5744,
                },
                adeptRole = {
                    2,
                    3,
                    4,
                },
                role = 2,
                skills = {
                },
                onfieldId = 2,
                id = 1,
                cid = "SMBayern02",
                number = 9,
            },
            {--Douglas Costa 2
                abilities = {
                    dribble = 10170,
                    intercept = 39393,
                    pass = 8742,
                    save = 1701,
                    shoot = 1712,
                    steal = 16404,
                },
                adeptRole = {
                    4,
                },
                role = 4,
                skills = {
                },
                onfieldId = 3,
                id = 2,
                cid = "SMBayern03",
                number = 11,
            },
            {--D. Alaba  3
                abilities = {
                    dribble = 16199,
                    intercept = 28509,
                    pass = 23149,
                    save = 2782,
                    shoot = 11574,
                    steal = 58866,
                },
                adeptRole = {
                    11,
                    15,
                    12,
                    13,
                    14,
                    16,
                    21,
                    20,
                    25,
                    22,
                    23,
                    24,
                    17,
                    18,
                    19,
                    2,
                    3,
                    4,
                },
                role = 11,
                skills = {
                },
                onfieldId = 4,
                id = 3,
                cid = "SMBayern04",
                number = 27,
            },
            {--A. Vidal    4
                abilities = {
                    dribble = 9246,
                    intercept = 24669,
                    pass = 8984,
                    save = 1804,
                    shoot = 8761,
                    steal = 20771,
                },
                adeptRole = {
                    12,
                },
                role = 12,
                skills = {
                },
                onfieldId = 5,
                id = 4,
                cid = "SMBayern08",
                number = 23,
            },
            {--A. Robben 5
                abilities = {
                    dribble = 52354,
                    intercept = 6229,
                    pass = 46482,
                    save = 3059,
                    shoot = 22939,
                    steal = 6229,
                },
                adeptRole = {
                    2,
                    3,
                    4,
                    5,
                    10,
                    7,
                    8,
                    9,
                    12,
                    13,
                    14,
                    15,
                },
                role = 14,
                skills = {
                },
                onfieldId = 6,
                id = 5,
                cid = "SMBayern01",
                number = 10,
            },
            {--Thiago Alcântara  6
                abilities = {
                    dribble = 4532,
                    intercept = 59979,
                    pass = 6429,
                    save = 1638,
                    shoot = 5786,
                    steal = 17304,
                },
                adeptRole = {
                    15,
                },
                role = 15,
                skills = {
                },
                onfieldId = 7,
                id = 6,
                cid = "SMBayern05",
                number = 6,
            },
            {--F. Ribéry 7
                abilities = {
                    dribble = 32775,
                    intercept = 2408,
                    pass = 19700,
                    save = 1602,
                    shoot = 22747,
                    steal = 2731,
                },
                adeptRole = {
                    21,
                },
                role = 21,
                skills = {
                },
                onfieldId = 8,
                id = 7,
                cid = "SMBayern07",
                number = 7,
            },
            {--J. Boateng 8
                abilities = {
                    dribble = 8203,
                    intercept = 22810,
                    pass = 8531,
                    save = 1564,
                    shoot = 1234,
                    steal = 29625,
                },
                adeptRole = {
                    22,
                },
                role = 22,
                skills = {
                },
                onfieldId = 9,
                id = 8,
                cid = "SMBayern06",
                number = 17,
            },
            {--M. Hummels  9
                abilities = {
                    dribble = 9391,
                    intercept = 6266,
                    pass = 22609,
                    save = 1774,
                    shoot = 64398,
                    steal = 6266,
                },
                adeptRole = {
                    24,
                },
                role = 24,
                skills = {
                },
                onfieldId = 10,
                id = 9,
                cid = "SMBayern09",
                number = 5,
            },
            {--F. Lahm    10
                abilities = {
                    dribble = 11752,
                    intercept = 18158,
                    pass = 8773,
                    save = 1716,
                    shoot = 1716,
                    steal = 36777,
                },
                adeptRole = {
                    20,
                    25,
                },
                role = 25,
                skills = {
                },
                onfieldId = 11,
                id = 10,
                cid = "SMBayern10",
                number = 21,
            },
            {--M. Neuer 0
                abilities = {
                    dribble = 11359,
                    intercept = 3062,
                    pass = 9100,
                    save = 89950,
                    shoot = 3062,
                    steal = 3062,
                },
                adeptRole = {
                    26,
                },
                role = 26,
                skills = {
                },
                onfieldId = 1,
                id = 11,
                cid = "SMBayern11",
                number = 1,
            },
        },
        captain = 10,
        field = "north",
        role = "Attack",
        tactics = {
            attackEmphasis = 3,
            competitionMentality = 4,
            defenseAggression = 3,
            defenseStrategy = 3,
            name = "",
            passTactic = 3,
            attackRhythm = 3,
        },
        tid = "SMBayern",
        sloganID = "",
        logo = "BayernPlayer",
        spectatorsID = "",
        teamID = "SMBayern",
        teamType = "player",
        homeShirt = {
            mask = "Mask_41",
            maskRedChannel = "0.713, 0.115, 0.115, 1.000",
            maskGreenChannel = "1.000, 1.000, 1.000, 1.000",
            maskBlueChannel = "0.714, 0.114, 0.114, 1.000",
            backNumColor = "1.000, 1.000, 1.000, 1.000",
            trouNumColor = "1.000, 1.000, 1.000, 1.000",
            chestAd = "telekom",
        },
        homeGkShirt = {
            mask = "Mask_18",
            maskRedChannel = "0.019, 0.333, 0.255, 1.000",
            maskGreenChannel = "0.392, 0.784, 0.431, 1.000",
            maskBlueChannel = "0.019, 0.333, 0.255, 1.000",
            backNumColor = "1.000, 1.000, 1.000, 1.000",
            trouNumColor = "1.000, 1.000, 1.000, 1.000",
            chestAd = "telekom",
        },
    },
}